#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmakeLnInclude interfacialModels
wmakeLnInclude interfacialCompositionModels
wmake lib phaseSystems
wmake lib interfacialModels
wmake lib interfacialCompositionModels
reactingTwoPhaseEulerFoam/Allwmake
reactingMultiphaseEulerFoam/Allwmake

# ----------------------------------------------------------------- end-of-file
