#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmake lib multiphaseSystem
wmake lib multiphaseCompressibleTurbulenceModels
wmake

# ----------------------------------------------------------------- end-of-file
