#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmake lib twoPhaseMixtureThermo
wmake
wmake compressibleInterDyMFoam

# ----------------------------------------------------------------- end-of-file
