#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmake lib twoPhaseSystem
wmake lib twoPhaseCompressibleTurbulenceModels
wmake

# ----------------------------------------------------------------- end-of-file
