#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmakeLnInclude interfacialModels
wmake lib twoPhaseSystem
wmake lib interfacialModels
wmake lib phaseCompressibleTurbulenceModels
wmake

# ----------------------------------------------------------------- end-of-file
