#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmakeLnInclude interfacialModels
wmake lib multiphaseSystem
wmake lib interfacialModels
wmake

# ----------------------------------------------------------------- end-of-file
