#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmake lib multiphaseMixture
wmake
wmake multiphaseInterDyMFoam

# ----------------------------------------------------------------- end-of-file
