#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=lib
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmakeCheckPwd "$WM_PROJECT_DIR/applications" || {
    echo "Allwmake error: Current directory is not \$WM_PROJECT_DIR/applications"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

set -x

#wmake -all utilities $*
#wmake -all solvers $*

# only decomposePar
# added by hf
# rm -f ../platforms/linux64swgccDPInt32Opt/bin/decomposePar
# wmake -all utilities/parallelProcessing/decomposePar $*

# only pisoFoam
# added by hf
#rm -f ../platforms/linux64swgccDPInt32Opt/bin/pisoFoam
#wmake -all solvers/incompressible/pisoFoam $*

# only simpleFoam
# added by hf
#rm -f ../platforms/linux64swgccDPInt32Opt/bin/simpleFoam
#wmake -all solvers/incompressible/simpleFoam $*

rm -f ../platforms/linux64swgccDPInt64Opt/bin/icoFoam
wmake -all solvers/incompressible/icoFoam $*
# rm -f ../platforms/linux64swgccDPInt64Opt/bin/scalarTransportFoam
# wmake -all solvers/basic/scalarTransportFoam


# ----------------------------------------------------------------- end-of-file
