#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmake lib mixtureViscosityModels
wmake lib relativeVelocityModels
wmake

# ----------------------------------------------------------------- end-of-file
