#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmake lib phaseChangeTwoPhaseMixtures
wmake
wmake interPhaseChangeDyMFoam

# ----------------------------------------------------------------- end-of-file
